### ISSUE TITLE
Get resource limits using getrlimit(2) / prlimit(2)

### ISSUE THREAD

**Issue by kamalmarhubi** [danburkert/procinfo-rs#16]
http://man7.org/linux/man-pages/man2/prlimit.2.html

**Comment by kamalmarhubi** [comment]
(I thought this was already implemented by parsing `/proc/<pid>/limits` but was confused with the Prometheus client library.)

**Comment by danburkert** [comment]
`rlimit` and `prlimit` have bindings in the `libc` crate, so perhaps use those?  I don't intend for this library to provide bindings for system/libc calls, although I do think it's appropriate to have a parser for `/proc/<pid>/limits`.  Another way of putting it: `procinfo` has a parser for `/proc/<pid>/cwd` even though everyone should prefer using ` std::env::current_dir`.

**Comment by kamalmarhubi** [comment]
Yeah, I would do it with those. If you think a parser is better, that's also something that I could do.

**Comment by danburkert** [comment]
I think a parser is in scope for this crate, so I would definitely accept a
PR. That being said, if I were trying to get this info as a normal
consumer, I would go the libc route, since it's likely more cross platform.

**Comment by kamalmarhubi** [comment]
Apparently `prlimit(2)` is Linux specific, and was only added in 2.6.36. The Centos 6 series uses 2.6.32, and will receive full updates through this May, and maintenance updates through 2020. So maybe the parser is the way to go.

**Comment by BlackYoup** [comment]
Hi,

I'm in need for that feature and might target more than Linux. I started something yesterday but I never really used nom and I'm still a beginner with rust, so this might take some days.

@kamalmarhubi do you have something on your side ? Or is it okay for me to do it ?

**Comment by danburkert** [comment]
Merged in #22, will cut a release soon (I want to get the fix in #21 in as well).
