### ISSUE TITLE
sysinfo

### ISSUE THREAD

**Issue by GuillaumeGomez** [danburkert/procinfo-rs#3]
Hi !

I wrote a [library](https://github.com/GuillaumeGomez/sysinfo) (I use it in my [process-viewer](https://github.com/GuillaumeGomez/process-viewer)) which does similar things. Maybe it could be nice to merge our work or join our efforts, no ?

**Comment by Hoverbear** [comment]
@GuillaumeGomez Process-viewer looks great! :)

**Comment by GuillaumeGomez** [comment]
It's just a little start, I wanna add some more functionnalities. I'll improve it once I have more time. Thanks for your review ! :)

**Comment by danburkert** [comment]
This is really cool.  It looks like `sysinfo` is doing some things outside the scope of this crate, but moving the `/proc` parsers here would be great.  It looks like you are using `/proc/meminfo` and `/proc/stat`, both of which are missing from `procinfo`.

As a side note, the `libc` crate already includes ffi bindings for `kill`, so you shouldn't need to redefine them, unless I'm missing something.  Also, you should take a look at `nix` for how to define signal values; the tldr is they are platform specific, and the definitions you have won't work for platforms like android.

**Comment by GuillaumeGomez** [comment]
I only get as small information as possible in order to doesn't impact performances (my `process-viewer` doesn't take that much for still too much). You can re-use my code of course, no problem with that but I think the goal of our crates isn't the same.

Thanks for tip, I didn't know `nix` and totally forgot to look at the `libc` to see if they already defined `kill`. I should change this !

**Comment by danburkert** [comment]
> I only get as small information as possible in order to doesn't impact performances

From what I've seen, the time to parse the files is typically dwarfed by the time to open the files.  You can check this out with the benchmarks in this repo, each has a version that opens the file and parses it, and a version that only parses it.

```bash
test loadavg::tests::bench_loadavg       ... bench:       6,626 ns/iter (+/- 95)
test loadavg::tests::bench_loadavg_parse ... bench:         475 ns/iter (+/- 0)
test statm::tests::bench_statm           ... bench:       2,560 ns/iter (+/- 1,428)
test statm::tests::bench_statm_parse     ... bench:         297 ns/iter (+/- 1)
test status::tests::bench_status         ... bench:      35,824 ns/iter (+/- 87)
test status::tests::bench_status_parse   ... bench:      24,179 ns/iter (+/- 96)
```

`status` is significantly more complicated than the others, which is why it's a bit heavier to parse.

**Comment by GuillaumeGomez** [comment]
Since those files are directly stored in RAM (`ls -l /proc` and you'll see a size of 0), what takes the most of time is certainly the parsing. And when it gets to 400 files to parse, it's really important.

**Comment by danburkert** [comment]
@GuillaumeGomez they are not stored in ram, they are created on demand in the kernel.  See `fs/proc/array.c`.  Those benchmarks are real; they show that opening the `load_avg` file, for instance, takes 6.2 microseconds (6.6 microseconds - 0.4 microseconds).

**Comment by danburkert** [comment]
Also if you are performance constrained you shouldn't be parsing a process's `status` file only to get the resident set size.  `statm` contains that information (albeit in different units), and as you can see above, is significantly faster to both open, and parse.

**Comment by GuillaumeGomez** [comment]
I learnt this a few years ago and remembered it wasn't stored on disk so I assumed it was in the RAM, thanks for correcting me !

I was struggling with cpu %, so I didn't improve performance yet. When I have finished to add sorting columns in process-viewer, I'll do it.

Thanks again for your help and the information you provided ! :)

**Comment by danburkert** [comment]
no problem, good luck with process-viewer, it looks great!

**Comment by GuillaumeGomez** [comment]
Thanks ! And like I said, don't hesitate to take a look at `sysinfo` source code if you need anything. ;)
