### ISSUE TITLE
Doesn't build on Mac OSX

### ISSUE THREAD

**Issue by crusty-dave** [danburkert/procinfo-rs#47]
I am not sure why this is trying to build on Darwin?

```
[target.'cfg(unix)'.dependencies]
procinfo = "0.4"

```

```
error[E0308]: mismatched types
   --> /Users/dweaver/.cargo/registry/src/github.com-1ecc6299db9ec823/procinfo-0.4.2/src/pid/status.rs:189:1
    |
189 | named!(parse_umask<mode_t>,     delimited!(tag!("Umask:\t"),     parse_u32_octal,    line_ending));
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected u16, found u32
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
help: you can convert an `u32` to `u16` and panic if the converted value wouldn't fit
    |
9   |          { $ crate :: IResult :: Done (i1, o.try_into().unwrap()) }
    |                                            ^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

**Comment by crusty-dave** [comment]
It looks like my bad, I should have used the following:

```
[target.x86_64-unknown-linux-gnu.dependencies]
procinfo = "0.4"

```

There is probably a more generic way to specify a Linux target.

**Comment by rabble** [comment]
`>  Compiling procfs v0.7.9
>    Compiling rand v0.7.3
> error[E0433]: failed to resolve: could not find `linux` in `os`
>   --> /Users/rabble/.cargo/registry/src/github.com-1ecc6299db9ec823/procfs-0.7.9/src/process/mod.rs:61:14
>    |
> 61 | use std::os::linux::fs::MetadataExt;
>    |              ^^^^^ could not find `linux` in `os`
> 
>    Compiling ctrlc v3.1.4
>    Compiling font-kit v0.7.1
> error[E0599]: no method named `st_uid` found for struct `std::fs::Metadata` in the current scope
>    --> /Users/rabble/.cargo/registry/src/github.com-1ecc6299db9ec823/procfs-0.7.9/src/process/mod.rs:544:23
>     |
> 544 |             owner: md.st_uid(),
>     |                       ^^^^^^ method not found in `std::fs::Metadata`
>     |
>     = help: items from traits can only be used if the trait is in scope
>     = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
>             `use std::os::macos::fs::MetadataExt;`
> 
> error[E0599]: no method named `st_mode` found for struct `std::fs::Metadata` in the current scope
>    --> /Users/rabble/.cargo/registry/src/github.com-1ecc6299db9ec823/procfs-0.7.9/src/process/mod.rs:745:30
>     |
> 745 |                     mode: md.st_mode() & libc::S_IRWXU,
>     |                              ^^^^^^^ method not found in `std::fs::Metadata`
>     |
>     = help: items from traits can only be used if the trait is in scope
>     = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
>             `use std::os::macos::fs::MetadataExt;`
> 
> error[E0308]: mismatched types
>    --> /Users/rabble/.cargo/registry/src/github.com-1ecc6299db9ec823/procfs-0.7.9/src/process/mod.rs:178:22
>     |
> 178 |         const READ = libc::S_IRUSR;
>     |                      ^^^^^^^^^^^^^ expected `u32`, found `u16`
> 
> error[E0308]: mismatched types
>    --> /Users/rabble/.cargo/registry/src/github.com-1ecc6299db9ec823/procfs-0.7.9/src/process/mod.rs:179:23
>     |
> 179 |         const WRITE = libc::S_IWUSR;
>     |                       ^^^^^^^^^^^^^ expected `u32`, found `u16`
> 
> error[E0308]: mismatched types
>    --> /Users/rabble/.cargo/registry/src/github.com-1ecc6299db9ec823/procfs-0.7.9/src/process/mod.rs:180:25
>     |
> 180 |         const EXECUTE = libc::S_IXUSR;
>     |                         ^^^^^^^^^^^^^ expected `u32`, found `u16`
> 
> error: aborting due to 6 previous errors
> 
> Some errors have detailed explanations: E0308, E0433, E0599.
> For more information about an error, try `rustc --explain E0308`.
> error: could not compile `procfs`.`
